services:
  prefect-server:
    image: prefecthq/prefect:3-latest    # Prefect 3 UI & API
    command: prefect server start --host 0.0.0.0 --port 4200
    ports:
      - "4200:4200"
    volumes:
      - prefect_data:/root/.prefect
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api

  prefect-worker:
    image: prefecthq/prefect:3-latest    # runs your tasks
    depends_on:
      - prefect-server
    command: >
      sh -c "prefect work-pool inspect default || prefect work-pool create --type process default &&
             prefect worker start --pool default"
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api

  app:
    build: .
    depends_on:
      - prefect-server
    env_file: .env                          # pull in GOOGLE_API_KEY=…
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
    volumes:
      - ./:/app                             # mount your entire project
      - ./photos_input:/app/photos_input
      - ./photos_output:/app/photos_output
    working_dir: /app
    command: python src/flow.py             # this will call image_classification_flow.serve(...)

volumes:
  prefect_data:
